const realData = {
  GK: [
    ['Alisson', 'Becker', 'Brasil', 'Liverpool'],
    ['Ederson', 'Moraes', 'Brasil', 'Manchester City'],
    ['Thibaut', 'Courtois', 'Bélgica', 'Real Madrid'],
    ['Marc-André', 'ter Stegen', 'Alemania', 'FC Barcelona'],
    ['Jan', 'Oblak', 'Eslovenia', 'Atlético de Madrid'],
    ['Gianluigi', 'Donnarumma', 'Italia', 'PSG'],
    ['Manuel', 'Neuer', 'Alemania', 'Bayern Munich'],
    ['Emiliano', 'Martínez', 'Argentina', 'Aston Villa'],
    ['Mike', 'Maignan', 'Francia', 'AC Milan'],
    ['Yann', 'Sommer', 'Suiza', 'Inter Milan'],
    ['Guglielmo', 'Vicario', 'Italia', 'Tottenham'],
    ['David', 'Raya', 'España', 'Arsenal'],
    ['Unai', 'Simón', 'España', 'Athletic Club'],
    ['Alex', 'Remiro', 'España', 'Real Sociedad'],
    ['Gregor', 'Kobel', 'Suiza', 'Borussia Dortmund']
  ],
  RB: [
    ['Kyle', 'Walker', 'Inglaterra', 'Manchester City'],
    ['Trent', 'Alexander-Arnold', 'Inglaterra', 'Liverpool'],
    ['Achraf', 'Hakimi', 'Marruecos', 'PSG'],
    ['Dani', 'Carvajal', 'España', 'Real Madrid'],
    ['Reece', 'James', 'Inglaterra', 'Chelsea'],
    ['Kieran', 'Trippier', 'Inglaterra', 'Newcastle'],
    ['Jeremie', 'Frimpong', 'Holanda', 'Bayer Leverkusen'],
    ['Pedro', 'Porro', 'España', 'Tottenham'],
    ['Ben', 'White', 'Inglaterra', 'Arsenal'],
    ['Jules', 'Koundé', 'Francia', 'FC Barcelona'],
    ['Giovanni', 'Di Lorenzo', 'Italia', 'Napoli'],
    ['Denzel', 'Dumfries', 'Holanda', 'Inter Milan'],
    ['Joao', 'Cancelo', 'Portugal', 'FC Barcelona'],
    ['Nahuel', 'Molina', 'Argentina', 'Atlético de Madrid'],
    ['Jesús', 'Navas', 'España', 'Sevilla']
  ],
  LB: [
    ['Andrew', 'Robertson', 'Escocia', 'Liverpool'],
    ['Alphonso', 'Davies', 'Canadá', 'Bayern Munich'],
    ['Theo', 'Hernández', 'Francia', 'AC Milan'],
    ['Ferland', 'Mendy', 'Francia', 'Real Madrid'],
    ['Federico', 'Dimarco', 'Italia', 'Inter Milan'],
    ['Alejandro', 'Grimaldo', 'España', 'Bayer Leverkusen'],
    ['Oleksandr', 'Zinchenko', 'Ucrania', 'Arsenal'],
    ['Destiny', 'Udogie', 'Italia', 'Tottenham'],
    ['Nuno', 'Mendes', 'Portugal', 'PSG'],
    ['Pervis', 'Estupiñán', 'Ecuador', 'Brighton'],
    ['Luke', 'Shaw', 'Inglaterra', 'Manchester United'],
    ['José', 'Gayà', 'España', 'Valencia'],
    ['Alejandro', 'Balde', 'España', 'FC Barcelona'],
    ['Raphaël', 'Guerreiro', 'Portugal', 'Bayern Munich'],
    ['Lucas', 'Digne', 'Francia', 'Aston Villa']
  ],
  CB: [
    ['Virgil', 'van Dijk', 'Holanda', 'Liverpool'],
    ['Ruben', 'Dias', 'Portugal', 'Manchester City'],
    ['William', 'Saliba', 'Francia', 'Arsenal'],
    ['Ronald', 'Araujo', 'Uruguay', 'FC Barcelona'],
    ['Eder', 'Militao', 'Brasil', 'Real Madrid'],
    ['Antonio', 'Rüdiger', 'Alemania', 'Real Madrid'],
    ['Alessandro', 'Bastoni', 'Italia', 'Inter Milan'],
    ['Matthijs', 'de Ligt', 'Holanda', 'Bayern Munich'],
    ['Gabriel', 'Magalhães', 'Brasil', 'Arsenal'],
    ['Cristian', 'Romero', 'Argentina', 'Tottenham'],
    ['John', 'Stones', 'Inglaterra', 'Manchester City'],
    ['Marquinhos', 'Correa', 'Brasil', 'PSG'],
    ['Min-jae', 'Kim', 'Corea del Sur', 'Bayern Munich'],
    ['Josko', 'Gvardiol', 'Croacia', 'Manchester City'],
    ['Nico', 'Schlotterbeck', 'Alemania', 'Borussia Dortmund']
  ],
  DM: [
    ['Rodri', 'Hernández', 'España', 'Manchester City'],
    ['Declan', 'Rice', 'Inglaterra', 'Arsenal'],
    ['Aurelien', 'Tchouaméni', 'Francia', 'Real Madrid'],
    ['Carlos', 'Casemiro', 'Brasil', 'Manchester United'],
    ['Martín', 'Zubimendi', 'España', 'Real Sociedad'],
    ['Joao', 'Palhinha', 'Portugal', 'Fulham'],
    ['Bruno', 'Guimarães', 'Brasil', 'Newcastle'],
    ['Eduardo', 'Camavinga', 'Francia', 'Real Madrid'],
    ['Manuel', 'Ugarte', 'Uruguay', 'PSG'],
    ['Wataru', 'Endo', 'Japón', 'Liverpool'],
    ['Thomas', 'Partey', 'Ghana', 'Arsenal'],
    ['Edson', 'Álvarez', 'México', 'West Ham'],
    ['Romeo', 'Lavia', 'Bélgica', 'Chelsea'],
    ['Yves', 'Bissouma', 'Mali', 'Tottenham'],
    ['Douglas', 'Luiz', 'Brasil', 'Aston Villa']
  ],
  CM: [
    ['Toni', 'Kroos', 'Alemania', 'Real Madrid'],
    ['Luka', 'Modric', 'Croacia', 'Real Madrid'],
    ['Frenkie', 'de Jong', 'Holanda', 'FC Barcelona'],
    ['Pedri', 'González', 'España', 'FC Barcelona'],
    ['Nicolo', 'Barella', 'Italia', 'Inter Milan'],
    ['Alexis', 'Mac Allister', 'Argentina', 'Liverpool'],
    ['Enzo', 'Fernández', 'Argentina', 'Chelsea'],
    ['Fabián', 'Ruiz', 'España', 'PSG'],
    ['Adrien', 'Rabiot', 'Francia', 'Juventus'],
    ['Pablo', 'Gavi', 'España', 'FC Barcelona'],
    ['Koke', 'Resurrección', 'España', 'Atlético de Madrid'],
    ['Hakan', 'Çalhanoğlu', 'Turquía', 'Inter Milan'],
    ['Mikel', 'Merino', 'España', 'Real Sociedad'],
    ['Youri', 'Tielemans', 'Bélgica', 'Aston Villa'],
    ['Mateo', 'Kovacic', 'Croacia', 'Manchester City']
  ],
  BBM: [
    ['Federico', 'Valverde', 'Uruguay', 'Real Madrid'],
    ['Jude', 'Bellingham', 'Inglaterra', 'Real Madrid'],
    ['Bernardo', 'Silva', 'Portugal', 'Manchester City'],
    ['Leon', 'Goretzka', 'Alemania', 'Bayern Munich'],
    ['Conor', 'Gallagher', 'Inglaterra', 'Chelsea'],
    ['Dominik', 'Szoboszlai', 'Hungría', 'Liverpool'],
    ['Scott', 'McTominay', 'Escocia', 'Manchester United'],
    ['Konrad', 'Laimer', 'Austria', 'Bayern Munich'],
    ['Weston', 'McKennie', 'USA', 'Juventus'],
    ['Ruben', 'Loftus-Cheek', 'Inglaterra', 'AC Milan'],
    ['Joelinton', 'Cassio', 'Brasil', 'Newcastle'],
    ['John', 'McGinn', 'Escocia', 'Aston Villa'],
    ['Rodrigo', 'de Paul', 'Argentina', 'Atlético de Madrid'],
    ['Marcel', 'Sabitzer', 'Austria', 'Borussia Dortmund'],
    ['Granit', 'Xhaka', 'Suiza', 'Bayer Leverkusen']
  ],
  AM: [
    ['Kevin', 'De Bruyne', 'Bélgica', 'Manchester City'],
    ['Martin', 'Odegaard', 'Noruega', 'Arsenal'],
    ['Jamal', 'Musiala', 'Alemania', 'Bayern Munich'],
    ['Florian', 'Wirtz', 'Alemania', 'Bayer Leverkusen'],
    ['Phil', 'Foden', 'Inglaterra', 'Manchester City'],
    ['James', 'Maddison', 'Inglaterra', 'Tottenham'],
    ['Bruno', 'Fernandes', 'Portugal', 'Manchester United'],
    ['Dani', 'Olmo', 'España', 'RB Leipzig'],
    ['Xavi', 'Simons', 'Holanda', 'RB Leipzig'],
    ['Cole', 'Palmer', 'Inglaterra', 'Chelsea'],
    ['Gio', 'Reyna', 'USA', 'Nottingham Forest'],
    ['Mason', 'Mount', 'Inglaterra', 'Manchester United'],
    ['Kai', 'Havertz', 'Alemania', 'Arsenal'],
    ['Brahim', 'Díaz', 'Marruecos', 'Real Madrid'],
    ['Lucas', 'Paquetá', 'Brasil', 'West Ham']
  ],
  RW: [
    ['Bukayo', 'Saka', 'Inglaterra', 'Arsenal'],
    ['Mohamed', 'Salah', 'Egipto', 'Liverpool'],
    ['Leroy', 'Sané', 'Alemania', 'Bayern Munich'],
    ['Raphinha', 'Belloli', 'Brasil', 'FC Barcelona'],
    ['Rodrygo', 'Goes', 'Brasil', 'Real Madrid'],
    ['Lamine', 'Yamal', 'España', 'FC Barcelona'],
    ['Jarrod', 'Bowen', 'Inglaterra', 'West Ham'],
    ['Ousmane', 'Dembélé', 'Francia', 'PSG'],
    ['Dejan', 'Kulusevski', 'Suecia', 'Tottenham'],
    ['Moussa', 'Diaby', 'Francia', 'Aston Villa'],
    ['Takefusa', 'Kubo', 'Japón', 'Real Sociedad'],
    ['Federico', 'Chiesa', 'Italia', 'Juventus'],
    ['Leon', 'Bailey', 'Jamaica', 'Aston Villa'],
    ['Antony', 'Santos', 'Brasil', 'Manchester United'],
    ['Marco', 'Asensio', 'España', 'PSG']
  ],
  LW: [
    ['Kylian', 'Mbappé', 'Francia', 'Real Madrid'],
    ['Vinicius', 'Junior', 'Brasil', 'Real Madrid'],
    ['Rafael', 'Leão', 'Portugal', 'AC Milan'],
    ['Khvicha', 'Kvaratskhelia', 'Georgia', 'Napoli'],
    ['Gabriel', 'Martinelli', 'Brasil', 'Arsenal'],
    ['Heung-min', 'Son', 'Corea del Sur', 'Tottenham'],
    ['Jeremy', 'Doku', 'Bélgica', 'Manchester City'],
    ['Luis', 'Díaz', 'Colombia', 'Liverpool'],
    ['Kaoru', 'Mitoma', 'Japón', 'Brighton'],
    ['Kingsley', 'Coman', 'Francia', 'Bayern Munich'],
    ['Jack', 'Grealish', 'Inglaterra', 'Manchester City'],
    ['Marcus', 'Rashford', 'Inglaterra', 'Manchester United'],
    ['Raheem', 'Sterling', 'Inglaterra', 'Chelsea'],
    ['Alejandro', 'Garnacho', 'Argentina', 'Manchester United'],
    ['Anthony', 'Gordon', 'Inglaterra', 'Newcastle']
  ],
  SS: [
    ['Antoine', 'Griezmann', 'Francia', 'Atlético de Madrid'],
    ['Joao', 'Felix', 'Portugal', 'FC Barcelona'],
    ['Christopher', 'Nkunku', 'Francia', 'Chelsea'],
    ['Paulo', 'Dybala', 'Argentina', 'AS Roma'],
    ['Thomas', 'Müller', 'Alemania', 'Bayern Munich'],
    ['Leandro', 'Trossard', 'Bélgica', 'Arsenal'],
    ['Diogo', 'Jota', 'Portugal', 'Liverpool'],
    ['Julian', 'Álvarez', 'Argentina', 'Manchester City'],
    ['Marcus', 'Thuram', 'Francia', 'Inter Milan'],
    ['Lautaro', 'Martínez', 'Argentina', 'Inter Milan'],
    ['Alexander', 'Isak', 'Suecia', 'Newcastle'],
    ['Lois', 'Openda', 'Bélgica', 'RB Leipzig'],
    ['Cody', 'Gakpo', 'Holanda', 'Liverpool'],
    ['Karim', 'Adeyemi', 'Alemania', 'Borussia Dortmund'],
    ['Joshua', 'Zirkzee', 'Holanda', 'Bologna']
  ],
  CF: [
    ['Erling', 'Haaland', 'Noruega', 'Manchester City'],
    ['Harry', 'Kane', 'Inglaterra', 'Bayern Munich'],
    ['Robert', 'Lewandowski', 'Polonia', 'FC Barcelona'],
    ['Victor', 'Osimhen', 'Nigeria', 'Napoli'],
    ['Ollie', 'Watkins', 'Inglaterra', 'Aston Villa'],
    ['Dusan', 'Vlahovic', 'Serbia', 'Juventus'],
    ['Álvaro', 'Morata', 'España', 'Atlético de Madrid'],
    ['Darwin', 'Núñez', 'Uruguay', 'Liverpool'],
    ['Ivan', 'Toney', 'Inglaterra', 'Brentford'],
    ['Gabriel', 'Jesus', 'Brasil', 'Arsenal'],
    ['Viktor', 'Gyökeres', 'Suecia', 'Sporting CP'],
    ['Rasmus', 'Hojlund', 'Dinamarca', 'Manchester United'],
    ['Benjamin', 'Sesko', 'Eslovenia', 'RB Leipzig'],
    ['Victor', 'Boniface', 'Nigeria', 'Bayer Leverkusen'],
    ['Nicolas', 'Jackson', 'Senegal', 'Chelsea']
  ]
};

module.exports = realData;
